/* ============================================================
   companies.js — FAANG company intel data
   ============================================================ */
(function () {
  window.SS = window.SS || {};

  window.SS.COMPANIES_INTEL = [
    /* ── Google ────────────────────────────────────────────── */
    {
      id: 'google',
      name: 'Google',
      color: '#4285F4',
      letter: 'G',
      emoji: '🔵',
      tagline: 'Design for billions. Explain every trade-off.',
      difficulty: 5,
      overview: 'Google invented many of the distributed systems patterns the industry now considers standard — MapReduce, Bigtable, Spanner, Chubby, Borg. Interviewers expect you to think at Google scale from the first minute. An answer designed for 10,000 users will not pass a Google system design round.',
      rounds: [
        { name: 'Recruiter Screen', duration: '30 min', type: 'hr', desc: 'Background check, role alignment, timeline.' },
        { name: 'Technical Phone Screen', duration: '45 min', type: 'coding', desc: 'Data structures & algorithms. LeetCode medium–hard. Judge is a senior engineer.' },
        { name: 'Onsite: Coding × 2', duration: '45 min each', type: 'coding', desc: 'Algorithms, complexity analysis, clean code. Both Google engineers and a host.' },
        { name: 'Onsite: System Design', duration: '45 min', type: 'design', desc: 'Design a large-scale distributed system. Interviewer acts as product manager asking clarifications.' },
        { name: 'Onsite: Behavioral (Googleyness)', duration: '45 min', type: 'behavioral', desc: 'Ambiguity handling, conflict resolution, leadership. Scores on a separate "Googleyness" axis.' },
      ],
      rubric: [
        { dimension: 'Problem Solving', weight: 'Critical', desc: 'Can you decompose the problem, identify constraints, and propose a structured solution independently?' },
        { dimension: 'Technical Knowledge', weight: 'Critical', desc: 'Deep understanding of distributed systems, databases, networking, and OS concepts.' },
        { dimension: 'Googleyness', weight: 'High', desc: 'Thriving in ambiguity, working collaboratively, doing the right thing even when it\'s hard.' },
        { dimension: 'Leadership', weight: 'High', desc: 'Evidence of driving impact, mentoring others, influencing cross-functional decisions.' },
        { dimension: 'Scale Awareness', weight: 'Critical', desc: 'All estimates and designs must reflect Google-scale constraints (10⁹ users, global distribution).' },
      ],
      topSystems: [
        { name: 'Search Autocomplete', frequency: 'Very High', estimatorId: 'search-autocomplete', note: 'Classic Google warm-up. Focus on trie vs inverted index debate.' },
        { name: 'Web Crawler', frequency: 'High', estimatorId: null, note: 'Politeness, distributed fetch queue, deduplication.' },
        { name: 'YouTube / Video Platform', frequency: 'High', estimatorId: 'video-streaming', note: 'CDN design, transcoding pipeline, adaptive streaming.' },
        { name: 'Google Drive / File Storage', frequency: 'Medium', estimatorId: null, note: 'Chunking, dedup, sync protocol, offline support.' },
        { name: 'Distributed Key-Value Store', frequency: 'Very High', estimatorId: 'key-value-store', note: 'Bigtable/Spanner-style. Expect deep dive on consistency.' },
        { name: 'Rate Limiter', frequency: 'Medium', estimatorId: 'rate-limiter', note: 'Token bucket vs leaky bucket, distributed enforcement.' },
      ],
      tips: [
        'Start with scale: state your assumptions in the first 2 minutes. "I\'m designing for 500M DAU globally" — don\'t wait to be asked.',
        'Use Google\'s own systems as vocabulary: Bigtable, Spanner, Pub/Sub, Chubby, Borg/Kubernetes. Familiarity signals cultural fit.',
        'When the interviewer pushes back, don\'t fold — defend your trade-off with reasoning. Googleyness includes intellectual courage.',
        'Always mention the CAP trade-off for your storage choice. CP for transactions, AP for social data — and say why.',
        'Draw the data flow first, then add components. Interviewers care about how data moves more than which boxes you draw.',
        'Google loves the "failure scenario" question. Proactively say: "What happens when this service is unavailable?"',
        'Quantify everything: QPS, storage per user per day, bandwidth. Use powers of 10 to estimate quickly.',
        '"Googleyness" is real — be collaborative, ask for feedback mid-design, say "I\'m not sure, here\'s how I\'d decide."',
      ],
      prepChecklist: [
        'Practice 3 full Bigtable/Spanner-style key-value store designs end-to-end',
        'Know consistent hashing cold — Google uses it everywhere',
        'Review Google\'s published papers: Bigtable, MapReduce, Spanner, Chubby',
        'Practice estimating at 10⁹ scale without a calculator',
        'Prepare 3 STAR stories for Googleyness (ambiguity, conflict, impact)',
        'Know HTTP/2 and gRPC — Google built both',
        'Study LevelDB and LSM trees — common deep-dive topic',
        'Practice the "then what?" drill: design a system, then fail every component',
      ],
      quotes: [
        'We want to see how you think, not just what you know. Talk through your reasoning — silence is your enemy.',
        'Candidates who struggle usually haven\'t estimated QPS before proposing a solution. Numbers first, then architecture.',
      ],
      uniqueTrait: 'Google has a separate "Googleyness" score that can veto an otherwise strong technical hire. Behavioral fit is not optional.',
    },

    /* ── Meta ──────────────────────────────────────────────── */
    {
      id: 'meta',
      name: 'Meta',
      color: '#0866FF',
      letter: 'M',
      emoji: '🔷',
      tagline: 'Move fast. Show product intuition. Then scale it.',
      difficulty: 4,
      overview: 'Meta (Facebook) builds some of the world\'s most complex social infrastructure — 3B users, real-time messaging at scale, news feed ranking, ads targeting, and live video. Their interviews strongly weight product thinking alongside technical depth. An architect who can\'t explain the user impact of their design choices will struggle at Meta.',
      rounds: [
        { name: 'Recruiter Screen', duration: '30 min', type: 'hr', desc: 'Role fit, compensation discussion, timeline.' },
        { name: 'Technical Phone Screen', duration: '45 min', type: 'coding', desc: 'Coding round, usually two problems. Meta often asks graph/tree problems.' },
        { name: 'Onsite: Coding × 2', duration: '45 min each', type: 'coding', desc: 'Algorithms + data structures. Clean, working code matters more than optimization.' },
        { name: 'Onsite: System Design', duration: '45 min', type: 'design', desc: 'Design a real social/consumer product. Interviewer plays PM. Product thinking is scored explicitly.' },
        { name: 'Onsite: Behavioral', duration: '45 min', type: 'behavioral', desc: 'Past impact, conflict resolution, cross-team collaboration. "Move Fast" culture fit.' },
      ],
      rubric: [
        { dimension: 'Product Intuition', weight: 'Critical', desc: 'Do you ask about the user experience before jumping to databases? Can you reason about product edge cases?' },
        { dimension: 'Technical Excellence', weight: 'Critical', desc: 'Clean system design, appropriate technology choices, awareness of failure modes.' },
        { dimension: 'Velocity', weight: 'High', desc: 'Meta values speed of decision-making. Interviewers dislike endless deliberation without commitment.' },
        { dimension: 'Impact & Ownership', weight: 'High', desc: 'Evidence of taking end-to-end ownership of hard problems, not just doing your part.' },
        { dimension: 'Collaboration', weight: 'Medium', desc: 'Meta is a large cross-functional org. Can you influence without authority?' },
      ],
      topSystems: [
        { name: 'News Feed / Timeline', frequency: 'Very High', estimatorId: 'news-feed', note: 'Fan-out on write vs read debate. Ranking pipeline. Pagination.' },
        { name: 'Messenger / Chat', frequency: 'Very High', estimatorId: 'chat-service', note: 'Real-time delivery, online presence, message ordering.' },
        { name: 'Notification Service', frequency: 'High', estimatorId: 'notifications', note: 'Push/pull, priority queues, delivery guarantees.' },
        { name: 'URL Shortener', frequency: 'Medium', estimatorId: 'url-shortener', note: 'Classic warmup. Focus on redirect latency and analytics.' },
        { name: 'Instagram Stories / Live', frequency: 'Medium', estimatorId: null, note: 'Ephemeral storage, CDN, real-time viewership counter.' },
        { name: 'Ad Targeting Engine', frequency: 'Medium', estimatorId: null, note: 'Real-time bidding, user graph, ML pipeline integration points.' },
      ],
      tips: [
        'Product first: before any architecture, ask "Who uses this? What are they trying to do?" Meta scores product intuition separately.',
        '"Move fast" means committing to decisions. Say "I\'ll go with X because Y — I acknowledge the trade-off is Z" rather than deliberating endlessly.',
        'Meta\'s news feed is their most complex system. Understand fan-out-on-write vs fan-out-on-read and when each makes sense.',
        'Real-time is a core Meta theme. Know WebSockets, pub/sub (Kafka), and presence systems cold.',
        'Business impact matters: "This design handles 2M notifications/sec, which is what Meta Messenger requires at peak."',
        'Graph problems appear in both coding and design rounds — social graph traversal, friend recommendations.',
        'Mention observability: "I\'d add metrics on queue depth, delivery latency, and failure rate." Meta has strong infra culture.',
        'For behavioral rounds: Meta\'s culture is about big impact. Prepare stories where you drove large, measurable outcomes.',
      ],
      prepChecklist: [
        'Design the Facebook News Feed end-to-end including ranking — know fan-out trade-offs',
        'Implement a simplified WebSocket chat server in your head',
        'Understand pub/sub (Kafka): partitions, consumer groups, delivery semantics',
        'Study Meta\'s open-source systems: RocksDB, Cassandra usage, TAO (Facebook\'s graph DB)',
        'Practice asking product clarification questions before any architecture',
        'Prepare 3 impact stories with metrics: "reduced latency by X%", "grew DAU by Y"',
        'Know the difference between push and pull notification models',
        'Review graph data structures — social networks are graphs',
      ],
      quotes: [
        'We want to hire people who build things, not people who talk about building things. Show momentum in your design.',
        'If you spend the first 10 minutes on architecture without mentioning the user, you\'ve already lost points on product sense.',
      ],
      uniqueTrait: 'Meta explicitly scores "Product Sense" — most candidates underestimate this. Start every design with user stories and use cases.',
    },

    /* ── Amazon ─────────────────────────────────────────────── */
    {
      id: 'amazon',
      name: 'Amazon',
      color: '#FF9900',
      letter: 'A',
      emoji: '🟠',
      tagline: 'Customer Obsession + Reliability + Frugality.',
      difficulty: 4,
      overview: 'Amazon\'s interview process is unlike any other FAANG — Leadership Principles (LPs) are not a soft add-on, they\'re equal in weight to technical performance. Every interviewer is assigned specific LPs to probe. A "Bar Raiser" — a senior engineer from a different team — can veto any hire. Reliability, cost-efficiency, and customer-centricity are expected in every design.',
      rounds: [
        { name: 'Online Assessment', duration: '90 min', type: 'coding', desc: 'Two LeetCode-style problems + behavioral questions. Automated scoring.' },
        { name: 'Technical Phone Screen', duration: '60 min', type: 'coding', desc: 'Coding + 2-3 LP behavioral questions. Interviewer assigned specific LPs.' },
        { name: 'Onsite: Coding × 2', duration: '60 min each', type: 'coding', desc: 'Algorithms + LP probing. Each round has both a coding problem and behavioral questions.' },
        { name: 'Onsite: System Design', duration: '60 min', type: 'design', desc: 'Design a large-scale system. Explicitly expected to address reliability, cost, and operational concerns.' },
        { name: 'Bar Raiser', duration: '60 min', type: 'behavioral', desc: 'A neutral senior engineer probes LPs deeply. Can override the hiring committee. Often the hardest round.' },
      ],
      rubric: [
        { dimension: 'Customer Obsession', weight: 'Critical', desc: 'Start from the customer need. How does your design serve the end user? What\'s the SLA they expect?' },
        { dimension: 'Frugality', weight: 'High', desc: 'Cost-conscious architecture. AWS pricing is not free. Mention cost trade-offs: reserved instances, data transfer, replication costs.' },
        { dimension: 'Reliability & Operational Excellence', weight: 'Critical', desc: 'Design for failure. SLAs, SLOs, circuit breakers, retry logic, graceful degradation.' },
        { dimension: 'Ownership', weight: 'High', desc: 'Amazon engineers own their services end-to-end. Show that you think about monitoring, alerting, and runbooks.' },
        { dimension: 'Leadership Principles Overall', weight: 'Critical', desc: '16 LPs assessed throughout. Invent and Simplify, Dive Deep, Deliver Results are most common in technical rounds.' },
      ],
      topSystems: [
        { name: 'Rate Limiter', frequency: 'Very High', estimatorId: 'rate-limiter', note: 'AWS API Gateway throttling patterns. Token bucket preferred.' },
        { name: 'Notification Service', frequency: 'High', estimatorId: 'notifications', note: 'SNS/SQS-inspired. Email, SMS, push. At-least-once delivery.' },
        { name: 'Key-Value Store (DynamoDB-style)', frequency: 'Very High', estimatorId: 'key-value-store', note: 'Eventual consistency, leaderless replication, DynamoDB single-table design.' },
        { name: 'Job Scheduler', frequency: 'High', estimatorId: 'job-scheduler', note: 'Distributed task queue, at-least-once execution, idempotency.' },
        { name: 'Order Management / Inventory', frequency: 'High', estimatorId: null, note: 'Distributed transactions, eventual consistency for inventory counts.' },
        { name: 'Delivery Tracking', frequency: 'Medium', estimatorId: null, note: 'Event-sourcing, real-time location updates, geospatial queries.' },
      ],
      tips: [
        'Frugality is tested: "I\'d use S3 Intelligent-Tiering to reduce storage costs for cold data by ~40%." Cost awareness = bonus points.',
        'Mention failure modes and recovery explicitly. Amazon obsesses over SLAs. "This service targets 99.99% availability — that\'s 52 minutes of downtime per year."',
        'For the Bar Raiser: they can ask about any LP in any context. Your best stories should cover Deliver Results, Ownership, and Invent & Simplify.',
        'Amazon uses "two-pizza teams" — design microservices that a small team can own end-to-end. Avoid monoliths.',
        'DynamoDB, SQS, SNS, S3, Kinesis — use AWS-native services in your designs. Amazon builds what it uses.',
        'Circuit breakers and retry with exponential backoff are expected in any Amazon design. Name them explicitly.',
        'Idempotency: Amazon is obsessed with it. Every write operation should be safe to retry.',
        'STAR format for behavioral questions — Situation, Task, Action, Result. Results need metrics.',
      ],
      prepChecklist: [
        'Memorize all 16 Leadership Principles — you\'ll be assessed on many of them',
        'Prepare 2 STAR stories per major LP (Ownership, Deliver Results, Customer Obsession, Invent & Simplify)',
        'Design a DynamoDB single-table schema for a complex use case',
        'Understand SQS (standard vs FIFO), SNS fan-out, Kinesis streams',
        'Practice adding reliability patterns to every design: circuit breaker, retry, DLQ',
        'Know CAP theorem for DynamoDB (AP, eventual consistency, tunable)',
        'Study the Amazon Builders\' Library — it\'s their actual engineering culture in writing',
        'Practice estimating AWS costs for your design components',
      ],
      quotes: [
        'We don\'t hire people who are just technically strong. Every Amazon engineer is a leader. The Bar Raiser round exists to enforce that standard.',
        'If your design doesn\'t mention what happens when a dependency is down, it\'s incomplete. We design for failure by default.',
      ],
      uniqueTrait: 'The Bar Raiser is a vetoing power held by a senior engineer from outside your target team. A strong technical interview can still fail if LPs are weak.',
    },

    /* ── Netflix ────────────────────────────────────────────── */
    {
      id: 'netflix',
      name: 'Netflix',
      color: '#E50914',
      letter: 'N',
      emoji: '🔴',
      tagline: 'Design for failure. Own your judgment. Ship with confidence.',
      difficulty: 5,
      overview: 'Netflix is arguably the most senior-skewed FAANG interviewer. They practice "hire only seniors" and their culture of Freedom and Responsibility means they expect engineers who make large, independent decisions without needing approval. Technical rounds focus on high-availability distributed systems, streaming infrastructure, and chaos engineering mindset. Culture fit can be a stronger filter than technical skill.',
      rounds: [
        { name: 'Recruiter Screen', duration: '30 min', type: 'hr', desc: 'Culture and role alignment. Netflix culture explicitly assessed here.' },
        { name: 'Technical Screen', duration: '60 min', type: 'coding', desc: 'System design or coding depending on role. Senior roles are often mostly system design.' },
        { name: 'Onsite: System Design × 2', duration: '60 min each', type: 'design', desc: 'Deep architecture discussions. Expect to design at Netflix scale: 200M subscribers.' },
        { name: 'Onsite: Coding', duration: '60 min', type: 'coding', desc: 'Algorithms, but often more practical / applied than pure LeetCode.' },
        { name: 'Culture/Judgment Round', duration: '60 min', type: 'behavioral', desc: 'The most Netflix-specific round. Assesses independent decision-making, communication, inclusion.' },
      ],
      rubric: [
        { dimension: 'Judgment & Ownership', weight: 'Critical', desc: 'Netflix does not like engineers who wait to be told what to do. Show that you\'d make the call and own the outcome.' },
        { dimension: 'High Availability Thinking', weight: 'Critical', desc: 'Design for failure from the first slide. Chaos engineering mindset: what breaks, how do you prevent it?' },
        { dimension: 'Communication', weight: 'Critical', desc: 'Netflix is a "written culture" — clarity and precision in communication is a core engineering competency.' },
        { dimension: 'Inclusion', weight: 'High', desc: 'Explicit dimension in Netflix rubric. How do you make your team more effective as a whole?' },
        { dimension: 'Curiosity', weight: 'Medium', desc: 'Netflix engineers are expected to learn continuously and be ahead of the industry.' },
      ],
      topSystems: [
        { name: 'Video Streaming Platform', frequency: 'Very High', estimatorId: 'video-streaming', note: 'CDN design, adaptive bitrate, encoding pipeline, playback session management.' },
        { name: 'CDN Design', frequency: 'Very High', estimatorId: null, note: 'Netflix Open Connect. Edge caching, cache invalidation, origin shielding.' },
        { name: 'Recommendation Engine', frequency: 'High', estimatorId: null, note: 'Collaborative filtering, real-time feature serving, A/B testing framework.' },
        { name: 'Notification Service', frequency: 'Medium', estimatorId: 'notifications', note: 'Marketing emails, push, in-app. At-scale delivery with throttling.' },
        { name: 'A/B Testing Platform', frequency: 'High', estimatorId: null, note: 'Experiment assignment, metric collection, statistical significance computation.' },
        { name: 'Content Ingestion Pipeline', frequency: 'Medium', estimatorId: null, note: 'Encoding, transcoding, DRM, multi-format delivery.' },
      ],
      tips: [
        'Design for 99.99% availability from the start. Netflix invented Chaos Monkey — failure testing is in their DNA.',
        'Netflix Open Connect (their CDN) is the most important infra piece to understand. Know how edge caching and ISP peering work.',
        'The "Freedom and Responsibility" culture means: Netflix wants engineers who say "I\'d make this call because..." — not "what do you think?"',
        'Adaptive bitrate streaming (HLS, DASH) is fundamental. Know how the player chooses quality levels based on bandwidth.',
        'The Keeper Test: "Would I fight to keep this person?" Your answers should demonstrate you are exceptional, not just competent.',
        'Netflix runs on AWS almost entirely — mention specific AWS services (Kinesis, S3, CloudFront, Redshift) in your designs.',
        'Microservices at Netflix: they have 1000+ services. Know service mesh, sidecar patterns, and distributed tracing (Zipkin).',
        'Their culture deck is public — read it. Interviewers actively probe the values in it: "Give me an example of when you\'ve demonstrated candor."',
      ],
      prepChecklist: [
        'Read and internalise the Netflix Culture Deck (it\'s public — google "Netflix Culture Deck Slideshare")',
        'Understand adaptive bitrate streaming: HLS, DASH, manifest files, segment download',
        'Design Netflix Open Connect (CDN) from scratch — their most-asked architecture question',
        'Study Chaos Engineering: Chaos Monkey, Simian Army, what failure injection looks like',
        'Know Netflix OSS: Hystrix (circuit breaker), Eureka (service discovery), Ribbon (LB)',
        'Prepare independent judgment stories: "I made this call without asking permission and here\'s the outcome"',
        'Practice designing at 200M user scale — Netflix\'s actual user count',
        'Study consistent hashing for CDN — how Netflix routes requests to nearest PoP',
      ],
      quotes: [
        'We don\'t want people who can follow process — we want people who can set the standard. Show me a decision you made that had real stakes.',
        'If you\'re waiting for the interviewer to lead you to the answer, you\'ve already signaled that you need a manager, not freedom.',
      ],
      uniqueTrait: 'Netflix has an explicit "Culture" interview round where your judgment, candor, and independence are the sole focus — no technical content. Many strong technical candidates fail here.',
    },

    /* ── Microsoft ──────────────────────────────────────────── */
    {
      id: 'microsoft',
      name: 'Microsoft',
      color: '#00A4EF',
      letter: 'M',
      emoji: '🪟',
      tagline: 'Systematic thinking, growth mindset, collaborative execution.',
      difficulty: 3,
      overview: 'Microsoft\'s interview culture is shaped by Satya Nadella\'s "growth mindset" philosophy — they want engineers who learn, collaborate, and improve, not just those who already know everything. The interview is more collaborative than adversarial, and interviewers often hint or guide more than at other companies. System design rounds focus on solid fundamentals, object-oriented decomposition, and extensibility.',
      rounds: [
        { name: 'Recruiter Screen', duration: '30 min', type: 'hr', desc: 'Role fit, compensation discussion, relocation logistics.' },
        { name: 'Technical Phone Screen', duration: '60 min', type: 'coding', desc: 'One coding problem + system design discussion. Interviewer may guide you.' },
        { name: 'Onsite: Coding × 2–3', duration: '60 min each', type: 'coding', desc: 'Data structures, algorithms, sometimes take-home style design in code.' },
        { name: 'Onsite: System Design', duration: '60 min', type: 'design', desc: 'High-level architecture with extensibility focus. Often asks to modify the design at the end.' },
        { name: 'As Appropriate (AA)', duration: '30–60 min', type: 'behavioral', desc: 'Senior leader interview for senior+ roles. Culture and strategic thinking. Can block or extend an offer.' },
      ],
      rubric: [
        { dimension: 'Problem Solving', weight: 'Critical', desc: 'Systematic decomposition. Think out loud. Show your process, not just your answer.' },
        { dimension: 'Technical Excellence', weight: 'Critical', desc: 'Solid fundamentals — APIs, data models, concurrency, scalability.' },
        { dimension: 'Growth Mindset', weight: 'High', desc: 'Respond well to hints. Show you can learn mid-interview. "That\'s a good point — let me revise my approach."' },
        { dimension: 'Collaboration', weight: 'High', desc: 'Microsoft is a large, matrixed org. Engineers must influence cross-team without authority.' },
        { dimension: 'Extensibility', weight: 'Medium', desc: 'Designs should be extensible. Microsoft often asks "how would you add feature X?" mid-round.' },
      ],
      topSystems: [
        { name: 'Search Autocomplete', frequency: 'Very High', estimatorId: 'search-autocomplete', note: 'Bing-style. Trie vs inverted index, ranking, personalisation.' },
        { name: 'Key-Value Store', frequency: 'High', estimatorId: 'key-value-store', note: 'Azure Cosmos DB-style. Multi-model, global distribution.' },
        { name: 'Video Conferencing (Teams)', frequency: 'High', estimatorId: 'zoom', note: 'Real-time audio/video, TURN/STUN, signaling, recording.' },
        { name: 'Rate Limiter', frequency: 'High', estimatorId: 'rate-limiter', note: 'Azure API Management. Sliding window rate limiting.' },
        { name: 'Notification Service', frequency: 'Medium', estimatorId: 'notifications', note: 'Push, email, in-app for Office 365 ecosystem.' },
        { name: 'Collaborative Editor (OneDrive / Office)', frequency: 'Medium', estimatorId: null, note: 'OT/CRDT for conflict-free concurrent editing, versioning.' },
      ],
      tips: [
        'Growth mindset is not just culture talk — when an interviewer hints, take it. They\'re testing whether you can learn in real time.',
        'Microsoft loves extensibility questions: "how would you add feature X?" Design with open/closed principle in mind from the start.',
        'Azure-native vocabulary scores well: Cosmos DB, Service Bus, Event Hub, Blob Storage, Azure Functions.',
        'Object-oriented decomposition is more valued at Microsoft than at other FAANGs. Define clear classes/services before scaling.',
        'The "As Appropriate" round for senior roles is a leadership screen. Prepare business impact stories, not just technical ones.',
        'Microsoft teams are large — show that you know how to work in a 100+ engineer org: documentation, API contracts, code reviews.',
        'Teams is their flagship product right now. Understanding WebRTC, signaling servers, and STUN/TURN is a strong differentiator.',
        'Microsoft values "Do more with less" — efficient use of compute, thoughtful API design. They run Azure at cost.',
      ],
      prepChecklist: [
        'Study Azure core services: Cosmos DB, Service Bus, Blob Storage, Azure Functions, AKS',
        'Design Microsoft Teams video calling infrastructure end-to-end',
        'Practice OOP decomposition before adding scale — class diagrams, API contracts',
        'Prepare extensibility responses: "Here\'s how I\'d add real-time collaboration to this design"',
        'Know WebRTC fundamentals: ICE, TURN/STUN, SDP, P2P vs relay',
        'Read about Cosmos DB multi-model API — Microsoft loves asking about it',
        'Prepare "growth mindset" stories: times you failed, learned, and improved measurably',
        'Study CRDT and OT for collaborative editing — rising topic at Microsoft',
      ],
      quotes: [
        'We\'re not trying to trick you. If you\'re going in the wrong direction, we\'ll tell you. We want to see how you respond to that.',
        'The best candidates use the hints we give them and build on them. That\'s how engineering actually works — nobody works alone.',
      ],
      uniqueTrait: 'Microsoft interviewers actively guide candidates during rounds. Taking hints gracefully and building on them is itself part of the evaluation — unlike Google/Netflix where you\'re expected to drive solo.',
    },

    /* ── Apple ──────────────────────────────────────────────── */
    {
      id: 'apple',
      name: 'Apple',
      color: '#1D1D1F',
      letter: '',
      emoji: '🍎',
      tagline: 'Privacy-first. Precision matters. Vertical integration.',
      difficulty: 4,
      overview: 'Apple\'s interview process is team-specific and less standardized than other FAANGs. Rounds are typically with the exact team you\'d join — interviewers are direct stakeholders. System design rounds emphasize privacy by design, privacy-preserving ML, on-device computation, and end-to-end encryption. Apple\'s products are deeply vertically integrated — hardware and software together.',
      rounds: [
        { name: 'Recruiter Screen', duration: '30 min', type: 'hr', desc: 'Role fit. Apple interviews are very team-specific — recruiter context matters a lot here.' },
        { name: 'Technical Phone Screen', duration: '60 min', type: 'coding', desc: 'Coding or design based on role. Very team-dependent.' },
        { name: 'Onsite: Coding × 2', duration: '60 min each', type: 'coding', desc: 'Practical coding, sometimes on a MacBook in Xcode if iOS-adjacent.' },
        { name: 'Onsite: System Design', duration: '60 min', type: 'design', desc: 'Architecture with Apple-specific concerns: privacy, on-device ML, iCloud sync.' },
        { name: 'Hiring Manager Round', duration: '60 min', type: 'behavioral', desc: 'Direct report to your future manager. Culture fit, career goals, team dynamics.' },
      ],
      rubric: [
        { dimension: 'Attention to Detail', weight: 'Critical', desc: 'Apple\'s brand is precision. Sloppy designs or vague answers are red flags.' },
        { dimension: 'Privacy by Design', weight: 'Critical', desc: 'Privacy is an Apple core value. Every design should address data minimization, on-device processing, and encryption.' },
        { dimension: 'Technical Depth', weight: 'High', desc: 'Apple expects deep specialization — they hire specialists, not generalists at senior levels.' },
        { dimension: 'Communication', weight: 'High', desc: 'Clear, precise, written-quality verbal communication.' },
        { dimension: 'Collaboration', weight: 'Medium', desc: 'Apple teams are small and tight-knit. Team fit matters greatly.' },
      ],
      topSystems: [
        { name: 'Notification Service (APNs)', frequency: 'Very High', estimatorId: 'notifications', note: 'Apple Push Notification service. Reliability, device token management, silent push.' },
        { name: 'iCloud Sync', frequency: 'High', estimatorId: null, note: 'Conflict resolution, delta sync, end-to-end encryption, offline support.' },
        { name: 'Key-Value Store', frequency: 'High', estimatorId: 'key-value-store', note: 'iCloud CloudKit, privacy-preserving data model.' },
        { name: 'On-device ML Inference', frequency: 'Medium', estimatorId: null, note: 'Core ML, federated learning, differential privacy.' },
        { name: 'Video/Audio Streaming', frequency: 'Medium', estimatorId: 'video-streaming', note: 'Apple TV+, FaceTime, HLS (Apple invented it).' },
        { name: 'Maps / Location', frequency: 'Low', estimatorId: null, note: 'Tile servers, real-time routing, privacy-preserving location.' },
      ],
      tips: [
        'Privacy is not an afterthought at Apple — it\'s architecture. "I\'d process this on-device using Core ML to avoid sending user data to the cloud."',
        'Apple invented HLS (HTTP Live Streaming). For streaming questions, know HLS segments, manifests, and adaptive bitrate deeply.',
        'Apple Push Notification service (APNs) is their most complex public infrastructure — a great system to design in depth.',
        'Vertical integration is core: designs should consider how software interacts with Apple silicon, the Secure Enclave, and hardware capabilities.',
        'End-to-end encryption is a first-class concern. Know how iMessage\'s E2E encryption works at a high level.',
        'Apple cultures values "doing fewer things, better" — don\'t over-engineer. One clean design beats three clever hacks.',
      ],
      prepChecklist: [
        'Understand APNs architecture — device tokens, payload limits, priority, background fetch',
        'Study iCloud CloudKit and how it handles conflict resolution in sync',
        'Know end-to-end encryption basics: key exchange, Diffie-Hellman, Signal Protocol',
        'Understand differential privacy and Apple\'s usage of it in keyboard analytics',
        'Know HLS deeply — segments, manifests, quality levels, DRM',
        'Prepare examples of privacy-preserving system design decisions',
        'Research the specific Apple team you\'re interviewing with — interviews are very team-specific',
      ],
      quotes: [
        'We care deeply about the experience from the user\'s perspective. A technically correct design that compromises privacy is not acceptable here.',
      ],
      uniqueTrait: 'Apple interviews are uniquely team-specific. Unlike Google or Amazon, there\'s no standardized question bank — you\'re interviewed by the people you\'d work with directly.',
    },

    /* ── Uber ───────────────────────────────────────────────── */
    {
      id: 'uber',
      name: 'Uber',
      color: '#000000',
      letter: 'U',
      emoji: '⚫',
      tagline: 'Real-time geo. High reliability. Marketplace systems.',
      difficulty: 4,
      overview: 'Uber operates one of the world\'s most complex real-time marketplaces: matching riders with drivers in milliseconds, computing dynamic pricing, routing millions of trips globally, and maintaining location accuracy for moving objects. Their system design interviews reflect this — geospatial systems, real-time matching, and marketplace dynamics are core topics.',
      rounds: [
        { name: 'Recruiter Screen', duration: '30 min', type: 'hr', desc: 'Role fit, team alignment, relocation.' },
        { name: 'Technical Phone Screen', duration: '60 min', type: 'coding', desc: 'Coding + short design. Often a geospatial or marketplace-adjacent problem.' },
        { name: 'Onsite: Coding × 2', duration: '60 min each', type: 'coding', desc: 'Algorithms with emphasis on efficiency for high-throughput systems.' },
        { name: 'Onsite: System Design', duration: '60 min', type: 'design', desc: 'Real-time system design. Geo-distribution and matching are common themes.' },
        { name: 'Onsite: Behavioral', duration: '60 min', type: 'behavioral', desc: 'Impact, ownership, operating under ambiguity (Uber moves fast).' },
      ],
      rubric: [
        { dimension: 'Real-time System Design', weight: 'Critical', desc: 'Can you design systems with sub-second latency requirements at Uber\'s scale (millions of trips/day)?' },
        { dimension: 'Geospatial Reasoning', weight: 'High', desc: 'Geohashing, spatial indexes, distance computation at scale. Core to Uber\'s business.' },
        { dimension: 'Reliability & Consistency', weight: 'High', desc: 'Trips involve money — payments, surge pricing must be consistent. Know distributed transactions.' },
        { dimension: 'Marketplace Thinking', weight: 'Medium', desc: 'Supply and demand dynamics, surge pricing systems, driver/rider matching algorithms.' },
        { dimension: 'Ownership', weight: 'High', desc: 'Uber moves fast and values engineers who own outcomes, not just tasks.' },
      ],
      topSystems: [
        { name: 'Ride Sharing / Matching', frequency: 'Very High', estimatorId: 'ride-sharing', note: 'Core Uber product. Matching, ETA computation, dynamic pricing.' },
        { name: 'Notification Service', frequency: 'High', estimatorId: 'notifications', note: 'Driver/rider alerts: push, SMS. Real-time delivery guarantees.' },
        { name: 'Rate Limiter', frequency: 'High', estimatorId: 'rate-limiter', note: 'Surge pricing API protection, driver dispatch rate limiting.' },
        { name: 'Key-Value Store', frequency: 'Medium', estimatorId: 'key-value-store', note: 'Schemaless (Cassandra) for trip data, driver location.' },
        { name: 'Job Scheduler', frequency: 'Medium', estimatorId: 'job-scheduler', note: 'Surge pricing computation, driver incentive cron jobs.' },
        { name: 'Geospatial Index', frequency: 'High', estimatorId: null, note: 'Geohash-based driver location lookup. H3 (Uber\'s own hex grid).' },
      ],
      tips: [
        'Geohashing is table stakes at Uber. Know how to index driver locations with geohash and query by proximity.',
        'Uber developed H3 (hexagonal geospatial grid) and open-sourced it. Mention it as a modern alternative to geohash.',
        'Real-time location streaming: 5M+ driver pings/second at peak. Know how to design for time-series location data.',
        'Surge pricing is a distributed rate/price computation problem. Think about consistency: two users in the same surge zone should see the same multiplier.',
        'Uber operates in 70+ countries — design for multi-region from the start. What happens when the São Paulo region goes down?',
        'Distributed transactions matter: when a trip is completed, the payment, the driver earnings update, and the receipt must all happen.',
        'Uber\'s stack: Go, Java for backend services; Kafka for event streaming; Cassandra, MySQL for storage; H3 for geo.',
        'ETA computation is a graph shortest-path problem at massive scale. Know Dijkstra\'s limitations and contraction hierarchies as a concept.',
      ],
      prepChecklist: [
        'Design the Uber rider-driver matching system end-to-end including surge pricing',
        'Understand geohash: encoding, neighbor lookup, radius search',
        'Study H3 (Uber\'s hexagonal grid system) — it\'s open source and frequently referenced',
        'Know how to design time-series storage for location pings (InfluxDB, Cassandra patterns)',
        'Design distributed surge pricing computation with consistency guarantees',
        'Understand Kafka for real-time event streaming at millions of events/second',
        'Study the CAP implications of trip state transitions (CP required for payments)',
        'Prepare ownership stories: problems you diagnosed and fixed end-to-end in production',
      ],
      quotes: [
        'Every feature we build needs to work in Lagos, London, and São Paulo simultaneously. Geo-distribution is not optional.',
        'Matching a rider with a driver in under 500ms while computing real-time ETAs for a city with 50,000 concurrent drivers — that\'s our baseline.',
      ],
      uniqueTrait: 'Uber invented H3 (hexagonal geospatial indexing) and Schemaless (a Cassandra-based storage system). Familiarity with their open-source contributions signals genuine interest in the company.',
    },
  ];
})();
